config/routes.rb
Cpp::Application.routes.draw do
  root :to => "posts#news"

  devise_for :users #,:controllers => { :registrations => "registrations" }

  resources :pages

  resources :attaches

  resources :comments

  resources :users

  resources :posts do
    resources :comments
  end

  resources :problems do
    resources :solutions
  end

  devise_scope :user do
    match "/users/sign_up/:initial_role" => 'devise/registrations#new', :as => 'new_user_with_role'
  end

  match "/solutions/unverified" => "solutions#unverified"
  match "/solutions/verified" => "solutions#verified"
  match "/solutions" => "solutions#all"

  match "/news" => "posts#news"

  match "/solutions/mine" => "solutions#mine"

  devise_scope :user do
    match '/confirm/:confirmation_token', :to => "devise/confirmations#show", :as => "user_confirm", :only_path => false
  end

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_many :solutions, :dependent => :destroy
  has_many :attaches, :as => :uploadable, :dependent => :destroy
  accepts_nested_attributes_for :attaches, :allow_destroy => true
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = current_user
    @problems_new = Problem.where("deadline >= ?", Time.now).order("deadline DESC")
    @problems_past = Problem.where("deadline < ?", Time.now).order("deadline DESC")
        respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @problems }
    end
  end

  def show
    @user = current_user
    #@problem = Problem.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @problem }
    end
  end

  def new
    #@problem = Problem.new
    @problem.attaches = [Attach.new()]
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @problem }
    end
  end

  def edit
    #@problem = Problem.find(params[:id])
  end

  def create
    #@problem = Problem.new(params[:problem])
    respond_to do |format|
      if @problem.save
        format.html { redirect_to(@problem, :notice => 'Problem was successfully created.') }
        format.xml { render :xml => @problem, :status => :created, :location => @problem }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @problem.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    #@problem = Problem.find(params[:id])
    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to(@problem, :notice => 'Problem was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @problem.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    #@problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to(problems_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
  def my_sol_count(problem)
    @solutions = Solution.find(:all, :conditions => {:user_id => @user.id, :problem_id => problem.id})
    return @solutions.count
  end
end

app/views/problems/_display.html.erb
<tr class="<%= cycle("even", "odd") %>">
  <td class="one"><%= link_to truncate(problem.title, :length => 18), problem %></td>
  <td class="two"><%= truncate(problem.problem, :length => 90) %></td>
  <td class="three"><%= conv(problem.deadline) %></td>

  <% if can? :update, Problem %>
      <td class="change"><%= link_to image_tag('edit-icon.png'), edit_problem_path(problem) %></td>
      <td class="delete"><%= link_to image_tag('delete-icon.png'), problem, :confirm => 'Вы уверены?', :method => :delete %></td>
  <% end %>
  <% if (can? :create, Solution) && (my_sol_count(problem) == 0) %>
      <td class="solve"><%= link_to image_tag('solve-icon.png'), new_problem_solution_path(problem) %></td>
  <% end %>
  <% if (can? :create, Problem) %>
      <td class="solutions"><%= link_to image_tag('solutions-icon.png'), problem_solutions_path(problem) %></td>
  <% end %>

</tr>

app/views/problems/_form.html.erb
<%= nested_form_for(@problem) do |f| %>
    <% if @problem.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

          <ul>
            <% @problem.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :Название %>
      <br/>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :Задача %>
      <br/>
      <%= f.text_area :problem %>
    </div>
    <div class="field">
      <%= f.label :Баллы %>
      <br/>
      <%= f.text_field :points, :size => 2 %>
    </div>
    <div class="field">
      <%= f.label :Срок_сдачи %>
      <br/>
      <%= f.text_field :deadline %>
    </div>
    <%= f.fields_for :attaches do |at| %>
        Название: <%= at.text_field :name %>
        <%= at.file_field :upfile %>
        <%= at.link_to_remove "Удалить файл" %>
    <% end %>
    <%= f.link_to_add "Добавить файл", :attaches %>
    <div class="actions">
      <%= f.submit "Отправить" %>
    </div>
<% end %>

app/views/problems/edit.html.erb
<h3>Изменение задачи</h3>

<%= render 'form' %>

<%= link_to 'Показать', @problem %> |
<%= link_to 'К списку задач', problems_path %>

app/views/problems/index.html.erb
<link type="text/css" href="css/themename/jquery-ui-1.8.18.custom.css" rel="Stylesheet" />
<script type="text/javascript" src="js/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="js/jquery-ui-1.8.18.custom.min.js"></script>

<h3>Список задач</h3>
<table class="problem-table">
  <tr>
    <th class="one">Название</th>
    <th class="two">Условие</th>
    <th class="three">Срок сдачи</th>
  </tr>

  <% @problems_new.each do |problem| %>
      <%= render :partial => "problems/display", :locals => {:problem => problem} %>
  <% end %>
</table>

<br><h3>Для этих задач срок сдачи уже прошел:</h3>

<table class="problem-table">
  <tr>
    <th class="one">Название</th>
    <th class="two">Условие</th>
    <th class="three">Срок сдачи</th>
  </tr>
  <% @problems_past.each do |problem| %>
      <%= render :partial => "problems/display", :locals => {:problem => problem} %>
  <% end %>
</table>

app/views/problems/new.html.erb
<h3>Новая задача</h3>

<%= render 'form' %>

<%= link_to 'К списку задач', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Название:</b>
  <%= @problem.title %>
</p>

<p>
  <b>Задача:</b>
  <%= @problem.problem %>
</p>

<p>
  <b>Баллы:</b>
  <%= @problem.points %>
</p>

<p>
  <b>Срок сдачи:</b>
  <%= @problem.deadline %>
</p>
<% if (can? :create, Solution) && (my_sol_count(@problem) == 0) %>
    <%= link_to "Решить", new_problem_solution_path(@problem) %>
<% end %>
<h2>Файлы:</h2>
<% @problem.attaches.each do |at| %>
    <%= at.name %> <%= link_to "Загрузить", at.upfile.url(:original, false) %><br>
<% end %>


<%= link_to 'Изменить', edit_problem_path(@problem) %> |
<%= link_to 'К списку задач', problems_path %>