config/routes.rb
Cpp::Application.routes.draw do
  root :to => "posts#news"

  devise_for :users #,:controllers => { :registrations => "registrations" }

  resources :pages

  resources :attaches

  resources :comments

  resources :users

  resources :posts do
    resources :comments
  end

  resources :problems do
    resources :solutions
  end

  devise_scope :user do
    match "/users/sign_up/:initial_role" => 'devise/registrations#new', :as => 'new_user_with_role'
  end

  match "/solutions/unverified" => "solutions#unverified"
  match "/solutions/verified" => "solutions#verified"
  match "/solutions" => "solutions#all"

  match "/news" => "posts#news"

  match "/solutions/mine" => "solutions#mine"

  devise_scope :user do
    match '/confirm/:confirmation_token', :to => "devise/confirmations#show", :as => "user_confirm", :only_path => false
  end

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed_in as <%= current_user.email %>. Not you? 
    <%= link_to "Signed_out", destroy_user_session_path %>
  <%  else %>
    <%= link_to "Signed_up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path%>
  <%  end %>
</div>
<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Body</th>
    <th>Commentable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.user.first_name  %></td>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= post.commentable %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Body:</b>
  <%= @page.body %>
</p>

<p>
  <b>Permalink:</b>
  <%= @page.permalink %>
</p>

<p>
  <b>Is active:</b>
  <%= @page.is_active %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>