config/routes.rb
Cpp::Application.routes.draw do
  root :to => "posts#news"

  devise_for :users #,:controllers => { :registrations => "registrations" }

  resources :pages

  resources :attaches

  resources :comments

  resources :users

  resources :posts do
    resources :comments
  end

  resources :problems do
    resources :solutions
  end

  devise_scope :user do
    match "/users/sign_up/:initial_role" => 'devise/registrations#new', :as => 'new_user_with_role'
  end

  match "/solutions/unverified" => "solutions#unverified"
  match "/solutions/verified" => "solutions#verified"
  match "/solutions" => "solutions#all"

  match "/news" => "posts#news"

  match "/solutions/mine" => "solutions#mine"

  devise_scope :user do
    match '/confirm/:confirmation_token', :to => "devise/confirmations#show", :as => "user_confirm", :only_path => false
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Сайт спецкурса по С++</title>
  <% if false %>
      <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/themes/ui-lightness/jquery-ui.css", "application" %>
  <% end %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag 'jquery', 'nested_form', "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/jquery-ui.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="images">
</div>
<div id="user_nav">
  <% if user_signed_in? %>
      <p>Вы авторизованы как <%= current_user.email %>. Не Вы?
        <%= link_to "Выйти", destroy_user_session_path %></p>
      <% if current_user.role == "student" %>
          <p>Количество баллов:
            <%= current_user.points %></p>

          <p>Количество непроверенных решений:
            <%= sol_number %> </p>
      <% end %>
  <% else %>
      <%= link_to "Зарегистрироваться", new_user_registration_path %>
      or <%= link_to "Войти", new_user_session_path %>
  <% end %>
</div>

<ul class="left-menu">
  <li>
    <% unless current_page?(problems_path) %>
        <%= link_to "Все задачи", problems_path %>
    <% else %>
        <span>Все задачи</span>
    <% end %>
  </li>
  <% if user_signed_in? && current_user.role == "student" %>
      <li>
        <% unless current_page?(solutions_mine_path) %>
            <%= link_to "Мои решения", solutions_mine_path %>
        <% else %>
            <span>Мои решения</span>
        <% end %></li>
  <% end %>
  <li>
    <% unless current_page?(users_path) %>
        <%= link_to "Таблица баллов", users_path %>
    <% else %>
        <span>Таблица баллов</span>
    <% end %></li>

  <li>
    <% unless current_page?(news_path) %>
        <%= link_to "Новости", news_path %>
    <% else %>
        <span>Новости</span>
    <% end %></li>

  <li>
    <% unless current_page?(posts_path) %>
        <%= link_to "Сообщения", posts_path %>
    <% else %>
        <span>Сообщения</span>
    <% end %></li>
  </li>

  <% if can? :create, Post %>
      <li>
        <% unless current_page?(new_post_path) %>
            <%= link_to 'Новое сообщение', new_post_path %>
        <% else %>
            <span>Новое сообщение</span>
        <% end %></li>
  <% end %>

  <% if can? :create, Problem %>
      <li>
        <% unless current_page?(new_problem_path) %>
            <%= link_to "Добавить задачу", new_problem_path %>
        <% else %>
            <span>Добавить задачу</span>
        <% end %></li>

      <li>
        <% unless current_page?(solutions_unverified_path) %>
            <%= link_to "Непроверенные решения", solutions_unverified_path %>
        <% else %>
            <span>Непроверенные решения</span>
        <% end %></li>

      <li>
        <% unless current_page?(solutions_path) %>
            <%= link_to "Все решения", solutions_path %>
        <% else %>
            <span>Все решения</span>
        <% end %></li>
  <% end %>
</ul>

<div id="yield">
  <%= yield %>
</div>

</body>
</html>